# Generated by Django 5.2.4 on 2025-07-17 12:06

import company.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, validators=[company.validators.ValidateName(field_name='Bank Name')])),
                ('account_holder_name', models.CharField(max_length=100, validators=[company.validators.ValidateName(field_name='Account Holder Name')])),
                ('account_no', models.CharField(max_length=30, validators=[company.validators.validate_account_number])),
                ('ifsc_code', models.CharField(max_length=20, validators=[company.validators.validate_ifsc_code])),
                ('address', models.TextField(validators=[company.validators.validate_address])),
                ('branch', models.CharField(max_length=100)),
                ('ad_code', models.CharField(blank=True, max_length=20, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=20, null=True)),
                ('opening_balance', models.FloatField(default=0.0, validators=[company.validators.ValidatePositiveAmount(field_name='Opening Balance')])),
                ('as_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(blank=True, choices=[('customer', 'Customer'), ('supplier', 'Supplier')], default='customer', max_length=10, null=True)),
                ('client_name', models.CharField(max_length=255, validators=[company.validators.ValidateName(field_name='Client name')])),
                ('mobile_number', models.CharField(max_length=10, validators=[company.validators.ValidatePhoneNumber()])),
                ('email', models.EmailField(max_length=254, validators=[company.validators.validate_email_custom])),
                ('gstin', models.CharField(blank=True, max_length=20, null=True, validators=[company.validators.validate_gst_format])),
                ('pan', models.CharField(blank=True, max_length=20, null=True, validators=[company.validators.validate_pan])),
                ('state', models.CharField(max_length=50, validators=[company.validators.ValidateName(field_name='State')])),
                ('billing_address', models.TextField(validators=[company.validators.validate_address])),
                ('billing_address_line2', models.CharField(blank=True, max_length=100, null=True, validators=[company.validators.ValidateIfPresentNotEmpty(field_name='Billing Address Line 2')])),
                ('shipping_address', models.TextField(blank=True, null=True, validators=[company.validators.ValidateIfPresentNotEmpty(field_name='Shipping Address')])),
                ('pincode_special_economic_zone', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, max_length=50, null=True, validators=[company.validators.ValidateIfPresentNotEmpty(field_name='City')])),
                ('credit_period', models.PositiveIntegerField(default=0, help_text='Days')),
                ('credit_limit', models.FloatField(default=0.0, validators=[company.validators.ValidatePositiveAmount(field_name='Credit Limit')])),
                ('opening_balance', models.FloatField(default=0.0, validators=[company.validators.ValidatePositiveAmount(field_name='Opening Balance')])),
                ('other_currency', models.BooleanField(default=False)),
                ('check_discount', models.BooleanField(default=False)),
                ('enable_multiple_address', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=55, validators=[company.validators.ValidateName(field_name='Company name')])),
                ('phone_no', models.CharField(max_length=10, validators=[company.validators.ValidatePhoneNumber()])),
                ('gst', models.CharField(blank=True, max_length=15, null=True, validators=[company.validators.validate_gst_format])),
                ('address', models.TextField(validators=[company.validators.validate_address])),
                ('type_of_company', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CashLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField(validators=[company.validators.ValidatePositiveAmount(field_name='Amount')])),
                ('transaction_type', models.CharField(choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')], max_length=7)),
                ('description', models.TextField(blank=True, null=True, validators=[company.validators.ValidateIfPresentNotEmpty(field_name='Description')])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cash_ledgers', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField(validators=[company.validators.ValidatePositiveAmount(field_name='Transaction Amount')])),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=6)),
                ('description', models.TextField(blank=True, null=True, validators=[company.validators.ValidateIfPresentNotEmpty(field_name='Transaction Description')])),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='company.bank')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bank_transactions', to='company.company')),
            ],
        ),
        migrations.AddField(
            model_name='bank',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='banks', to='company.company'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, validators=[company.validators.ValidatePhoneNumber()])),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, validators=[company.validators.ValidateName(field_name='Item name')])),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('quantity', models.FloatField(validators=[company.validators.ValidatePositiveAmount(field_name='Quantity')])),
                ('description', models.TextField(validators=[company.validators.validate_address])),
                ('tax', models.FloatField(blank=True, null=True, validators=[company.validators.ValidatePositiveAmount(field_name='Tax')])),
                ('price', models.FloatField(help_text='Base price per unit', validators=[company.validators.ValidatePositiveAmount(field_name='Price')])),
                ('selling_price', models.FloatField(blank=True, default=0.0, help_text='Selling price per unit', null=True, validators=[company.validators.ValidatePositiveAmount(field_name='Selling Price')])),
                ('deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.company')),
                ('tax_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.taxtype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.unit')),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='company.company')),
            ],
            options={
                'unique_together': {('name', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=10, validators=[company.validators.ValidatePhoneNumber()])),
                ('type_of_company', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], max_length=10)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, related_name='companies', to='company.owner'),
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100, validators=[company.validators.ValidateName(field_name='Supplier Name')])),
                ('invoice_number', models.CharField(max_length=100, unique=True, validators=[company.validators.ValidateInvoiceNumber()])),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('total_price', models.FloatField(default=0.0)),
                ('deleted', models.BooleanField(default=False)),
                ('paid_amt', models.FloatField(default=0.0, validators=[company.validators.ValidatePositiveAmount(field_name='Paid Amount')])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_invoices', to='company.company')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.paymentmode')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.paymentstatus')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.paymenttype')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True, validators=[company.validators.ValidateInvoiceNumber()])),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('final_discount_applicable', models.BooleanField(default=False)),
                ('final_discount', models.FloatField(default=0.0, validators=[company.validators.ValidateDiscount(field_name='Final Discount')])),
                ('total_price', models.FloatField(default=0.0)),
                ('deleted', models.BooleanField(default=False)),
                ('received_amt', models.FloatField(default=0.0, validators=[company.validators.ValidatePositiveAmount(field_name='Received Amount')])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices', to='company.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices', to='company.company')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.paymentmode')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.paymentstatus')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.paymenttype')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[company.validators.ValidatePositiveAmount(field_name='Item Quantity')])),
                ('discount_applicable', models.BooleanField(default=False)),
                ('discount', models.FloatField(default=0.0, validators=[company.validators.ValidateDiscount(field_name='Item Discount')])),
                ('line_total', models.FloatField(default=0.0)),
                ('deleted', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='company.salesinvoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.item')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, validators=[company.validators.ValidateName(field_name='Purchase Item Name')])),
                ('quantity', models.FloatField(validators=[company.validators.ValidatePositiveAmount(field_name='Purchase Quantity')])),
                ('cost_price', models.FloatField(help_text='Unit purchase price (cost)', validators=[company.validators.ValidatePositiveAmount(field_name='Cost Price')])),
                ('line_total', models.FloatField(blank=True, default=0.0)),
                ('deleted', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='company.purchaseinvoice')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.unit')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCompanyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_links', to='company.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_links', to='company.employee')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_mappings', to='company.jobrole')),
            ],
            options={
                'unique_together': {('employee', 'company')},
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_view_specific', models.BooleanField(default=False)),
                ('can_get_using_post', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='module_permissions', to='company.company')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='permissions', to='company.jobrole')),
            ],
            options={
                'unique_together': {('job_role', 'company', 'module_name')},
            },
        ),
    ]
