# Generated by Django 5.2.4 on 2025-07-12 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('account_no', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('branch', models.CharField(max_length=100)),
                ('ad_code', models.CharField(blank=True, max_length=20, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=20, null=True)),
                ('opening_balance', models.FloatField(default=0.0)),
                ('as_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(blank=True, choices=[('customer', 'Customer'), ('supplier', 'Supplier')], max_length=10, null=True)),
                ('client_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gstin', models.CharField(blank=True, max_length=20, null=True)),
                ('pan', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(max_length=50)),
                ('billing_address', models.TextField()),
                ('billing_address_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('pincode_special_economic_zone', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_period', models.PositiveIntegerField(default=0, help_text='Days')),
                ('credit_limit', models.FloatField(default=0.0)),
                ('opening_balance', models.FloatField(default=0.0)),
                ('other_currency', models.BooleanField(default=False)),
                ('check_discount', models.BooleanField(default=False)),
                ('enable_multiple_address', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=15)),
                ('gst', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('type_of_company', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='company.bank')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='company.company')),
            ],
        ),
        migrations.AddField(
            model_name='bank',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='company.company'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('quantity', models.FloatField()),
                ('description', models.TextField()),
                ('tax', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(help_text='Base price per unit')),
                ('selling_price', models.FloatField(blank=True, default=0.0, help_text='Selling price per unit', null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.company')),
                ('tax_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.taxtype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=15)),
                ('type_of_company', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], max_length=10)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='companies', to='company.owner'),
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('total_price', models.FloatField(default=0.0)),
                ('paid_amt', models.FloatField(default=0.0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_invoices', to='company.company')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.paymentmode')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.paymentstatus')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.paymenttype')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('final_discount_applicable', models.BooleanField(default=False)),
                ('final_discount', models.FloatField(default=0.0)),
                ('deleted', models.BooleanField(default=False)),
                ('total_price', models.FloatField(default=0.0)),
                ('received_amt', models.FloatField(default=0.0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices', to='company.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices', to='company.company')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.paymentmode')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.paymentstatus')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.paymenttype')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('discount_applicable', models.BooleanField(default=False)),
                ('discount', models.FloatField(default=0.0)),
                ('line_total', models.FloatField(default=0.0)),
                ('deleted', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='company.salesinvoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.item')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('cost_price', models.FloatField(help_text='Unit purchase price (cost)')),
                ('line_total', models.FloatField(blank=True, default=0.0)),
                ('deleted', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='company.purchaseinvoice')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.unit')),
            ],
        ),
    ]
