# Generated by Django 5.2.4 on 2025-07-09 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=15)),
                ('gst', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('type_of_company', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('gst', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_no', models.CharField(max_length=15)),
                ('deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clients', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('quantity', models.FloatField()),
                ('description', models.TextField()),
                ('tax', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(help_text='Base price per unit')),
                ('selling_price', models.FloatField(blank=True, default=0.0, help_text='Selling price per unit', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.company')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.taxtype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=15)),
                ('type_of_company', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], max_length=10)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='companies', to='company.owner'),
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('total_price', models.FloatField(default=0.0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_invoices', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('final_discount_applicable', models.BooleanField(default=False)),
                ('final_discount', models.FloatField(default=0.0)),
                ('total_price', models.FloatField(default=0.0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices', to='company.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('discount_applicable', models.BooleanField(default=False)),
                ('discount', models.FloatField(default=0.0)),
                ('line_total', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='company.salesinvoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.item')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('cost_price', models.FloatField(help_text='Unit purchase price (cost)')),
                ('line_total', models.FloatField(blank=True, default=0.0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='company.purchaseinvoice')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.unit')),
            ],
        ),
    ]
