# Generated by Django 5.2.4 on 2025-07-17 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.jobrole'),
        ),
        migrations.AlterUniqueTogether(
            name='modulepermission',
            unique_together={('job_role', 'module_name')},
        ),
    ]
