# Generated by Django 5.2.4 on 2025-07-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='selling_price',
            field=models.FloatField(blank=True, default=0.0, help_text='Selling price per unit (before or after tax, your choice)', null=True),
        ),
    ]
