# Generated by Django 5.2.4 on 2025-07-14 05:58

import company.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_holder_name',
            field=models.CharField(max_length=100, validators=[company.validators.ValidateName(field_name='Account Holder Name')]),
        ),
        migrations.AlterField(
            model_name='bank',
            name='account_no',
            field=models.CharField(max_length=30, validators=[company.validators.validate_account_number]),
        ),
        migrations.AlterField(
            model_name='bank',
            name='address',
            field=models.TextField(validators=[company.validators.validate_address]),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(max_length=100, validators=[company.validators.ValidateName(field_name='Bank Name')]),
        ),
        migrations.AlterField(
            model_name='bank',
            name='ifsc_code',
            field=models.CharField(max_length=20, validators=[company.validators.validate_ifsc_code]),
        ),
        migrations.AlterField(
            model_name='bank',
            name='opening_balance',
            field=models.FloatField(default=0.0, validators=[company.validators.ValidatePositiveAmount(field_name='Opening Balance')]),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='amount',
            field=models.FloatField(validators=[company.validators.ValidatePositiveAmount(field_name='Transaction Amount')]),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[company.validators.ValidateIfPresentNotEmpty(field_name='Transaction Description')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='billing_address',
            field=models.TextField(validators=[company.validators.validate_address]),
        ),
        migrations.AlterField(
            model_name='client',
            name='billing_address_line2',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[company.validators.ValidateIfPresentNotEmpty(field_name='Billing Address Line 2')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[company.validators.ValidateIfPresentNotEmpty(field_name='City')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=255, validators=[company.validators.ValidateName(field_name='Client name')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('supplier', 'Supplier')], default='customer', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='credit_limit',
            field=models.FloatField(default=0.0, validators=[company.validators.ValidatePositiveAmount(field_name='Credit Limit')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, validators=[company.validators.validate_email_custom]),
        ),
        migrations.AlterField(
            model_name='client',
            name='gstin',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[company.validators.validate_gst_format]),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile_number',
            field=models.CharField(max_length=10, validators=[company.validators.ValidatePhoneNumber()]),
        ),
        migrations.AlterField(
            model_name='client',
            name='opening_balance',
            field=models.FloatField(default=0.0, validators=[company.validators.ValidatePositiveAmount(field_name='Opening Balance')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='pan',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[company.validators.validate_pan]),
        ),
        migrations.AlterField(
            model_name='client',
            name='shipping_address',
            field=models.TextField(blank=True, null=True, validators=[company.validators.ValidateIfPresentNotEmpty(field_name='Shipping Address')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(max_length=50, validators=[company.validators.ValidateName(field_name='State')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(validators=[company.validators.validate_address]),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=55, validators=[company.validators.ValidateName(field_name='Company name')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='gst',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[company.validators.validate_gst_format]),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, related_name='companies', to='company.owner'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_no',
            field=models.CharField(max_length=10, validators=[company.validators.ValidatePhoneNumber()]),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(validators=[company.validators.validate_address]),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=100, validators=[company.validators.ValidateName(field_name='Item name')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(help_text='Base price per unit', validators=[company.validators.ValidatePositiveAmount(field_name='Price')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.FloatField(validators=[company.validators.ValidatePositiveAmount(field_name='Quantity')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='selling_price',
            field=models.FloatField(blank=True, default=0.0, help_text='Selling price per unit', null=True, validators=[company.validators.ValidatePositiveAmount(field_name='Selling Price')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='tax',
            field=models.FloatField(blank=True, null=True, validators=[company.validators.ValidatePositiveAmount(field_name='Tax')]),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_no',
            field=models.CharField(max_length=10, validators=[company.validators.ValidatePhoneNumber()]),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_number',
            field=models.CharField(max_length=100, unique=True, validators=[company.validators.ValidateInvoiceNumber()]),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='paid_amt',
            field=models.FloatField(default=0.0, validators=[company.validators.ValidatePositiveAmount(field_name='Paid Amount')]),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier_name',
            field=models.CharField(max_length=100, validators=[company.validators.ValidateName(field_name='Supplier Name')]),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='cost_price',
            field=models.FloatField(help_text='Unit purchase price (cost)', validators=[company.validators.ValidatePositiveAmount(field_name='Cost Price')]),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='item_name',
            field=models.CharField(max_length=100, validators=[company.validators.ValidateName(field_name='Purchase Item Name')]),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='quantity',
            field=models.FloatField(validators=[company.validators.ValidatePositiveAmount(field_name='Purchase Quantity')]),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='final_discount',
            field=models.FloatField(default=0.0, validators=[company.validators.ValidateDiscount(field_name='Final Discount')]),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(max_length=100, unique=True, validators=[company.validators.ValidateInvoiceNumber()]),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='received_amt',
            field=models.FloatField(default=0.0, validators=[company.validators.ValidatePositiveAmount(field_name='Received Amount')]),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='discount',
            field=models.FloatField(default=0.0, validators=[company.validators.ValidateDiscount(field_name='Item Discount')]),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[company.validators.ValidatePositiveAmount(field_name='Item Quantity')]),
        ),
    ]
