# Generated by Django 5.2.4 on 2025-07-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_item_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='price_per_unit',
            field=models.FloatField(blank=True, default=0, help_text='Price per unit after tax (final selling price)', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_price',
            field=models.FloatField(blank=True, default=0, help_text='Total = price_per_unit * quantity', null=True),
        ),
    ]
