# Generated by Django 5.2.4 on 2025-07-09 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_salesinvoiceitem_line_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tax_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.taxtype'),
        ),
    ]
