# Generated by Django 5.2.4 on 2025-07-14 13:19

import company.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_bank_account_holder_name_alter_bank_account_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField(validators=[company.validators.ValidatePositiveAmount(field_name='Amount')])),
                ('transaction_type', models.CharField(choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')], max_length=7)),
                ('description', models.TextField(blank=True, null=True, validators=[company.validators.ValidateIfPresentNotEmpty(field_name='Description')])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_ledgers', to='company.company')),
            ],
        ),
    ]
