# Generated by Django 5.2.4 on 2025-07-19 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_employee_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeecompanymap',
            unique_together={('employee', 'company', 'job_role')},
        ),
        migrations.AddField(
            model_name='employeecompanymap',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_employees', to='company.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_employees', to='company.jobrole'),
        ),
    ]
