# Generated by Django 5.2.4 on 2025-07-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_jobrole_employee_modulepermission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modulepermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jobrole',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
