# Generated by Django 5.2.4 on 2025-07-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_employeecompanymap_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_role',
        ),
        migrations.RemoveField(
            model_name='employeecompanymap',
            name='is_primary',
        ),
    ]
